apiVersion: certmanager.k8s.io/v1alpha
kind: Certificate
metadata:
  name: multik8s-jpbarbosa-com-tls
spec:
  secretName: multik8s-jpbarbosa-com
  issuerRef:
    name: letsencrypt-prod
    kind: CLusterIssuer
  commonName: multik8s.jpbarbosa.com
  dnsNames:
    - multik8s.jpbarbosa.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multik8s.jpbarbosa.com
